name: Build and Test

on:
  # Allows to run workflow manually from Actions tab
  workflow_dispatch:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  # Trigger the workflow on all pull requests
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      - name: Mount Bazel cache 
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build 
        run: bazel build ...
